version: '3'
services:
  fako_ui:
    build:
      context: .
      dockerfile: build_docker/Dockerfile_ui
    ports:
      - '80:3000'
    environment:
      APP_PORT: 3000
      BACKEND_PORT: 8080
      BACKEND_HOST: 'ngx_mocker' 
  ngx_mocker:
    build:
      context: .
      dockerfile: build_docker/Dockerfile_ngx_mocker
    ports:
    - '8080:8080'
